version: '3.11'

services:
  neo4j:
    build: ./dataBase
    env_file:
      - ../env
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NE04J_AUTH: "neo4j/${NEO4J_PASSWORD}"
      NE04] _apoc_export_file_enabled: "true" 
      NE04J_apoc_import_file_enabled: "true"
      NE04]_apoc_import_file_use_neo4j_config: "true"
      NE04] _dbms_security_procedures_unrestricted: "apoc.*" 
    volumes:
      - ./data: /data